### PR TITLE
desktop/remote_desktop: Add support for ConnectToEIS

### PR DESCRIPTION
**Pull request by whot**
admittedly this is untested but it *looks* correct :)

### CODE REVIEW

**Comment by whot** [comment]
remaining CI failures are unrelated: `error: failed to select a version for the requirement gdk4-wayland = "^0.7"` - I used 0.8 locally and that made it compile but I don't know if there are any side-effects other than that

**Comment by bilelmoussaoui** [comment]
The build should pass once https://github.com/bilelmoussaoui/ashpd/pull/147 lands. Thanks!

**Comment by bilelmoussaoui** [comment]
Would need a rebase

**Comment by whot** [comment]
thanks! (sorry for the delay, still traveling)

**Pull request merged**
