### PR TITLE
window_identifier: return an error if from_native is called multiple times

### PR DESCRIPTION
**Pull request by Cogitri**
I havent adjusted the other docs yet since I first wanted to see if this approach is OK.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Would be nice to return the same error for the gtk3 version as well. Also maybe we can make from_native return an error itself instead of silently falling back to the default implementation

**Comment by Cogitri** [comment]
Sure, I’ll implement that later today, thanks for checking this out :)

**Comment by bilelmoussaoui** [comment]
@Cogitri Interesting, maybe we should ask upstream gtk why we can't have the same behaviour in gtk4 as well?

**Comment by Cogitri** [comment]
image

So basically its not in GTK4 because no one implemented it (yet)

**Comment by bilelmoussaoui** [comment]
Worked around it on ashpd side

**Pull request closed without merging**
