### PR TITLE
Fix deserialization in input_capture portal

### LINKED ISSUE #187: input_capture portal Signals are not working
The `receive_activate()` / `receive_deactivate()` Streams on the `input_capture` portal never yield any Result.

I did some digging and could narrow it down a bit:

`receive_activated` calls `signal("Activated")` which yields a Stream that filter-maps on the result of `msg.body::<Activated>().ok()`

So I tried to replicated the `body()` call manually and it always throws the following error:
```
called `Result::unwrap()` on an `Err` value: Variant(Message("invalid type: character `o`, expected `v`, `a` or `(`"))
```
Which then of course results in the signal getting filtered by the filter_map call.

This error in `body` is originated from `zvariant::from_slice_fds_for_dynamic_signature` -> `deserializer_for_signature` -> ... -> `deserialize_seq` where it ultimately fails in `zbus/zvariant/src/dbus/de.rs:347` because it does not expect an `o`.

### PR DESCRIPTION
**Pull request by feschber**
closes #187

### CODE REVIEW

**Comment by A6GibKm** [comment]
Thanks! Just for the record, could you please add a small description on how this was tested here?

**Comment by feschber** [comment]
the example I linked in the issue correctly deserializes the activation token now

**Comment by feschber** [comment]
https://github.com/feschber/lan-mouse/tree/libei-producer this works correctly now

**Comment by bilelmoussaoui** [comment]
Oh nooo. That is really stupid from my side. Would you mind checking other types that uses signature = dict and see if they use the correct deserialization derive macro?

Thanks a lot

**Comment by feschber** [comment]
> Oh nooo. That is really stupid from my side. Would you mind checking other types that uses signature = dict and see if they use the correct deserialization derive macro?
> 
> Thanks a lot

No problem, I could 100% see myself doing the same.
I did a quick grep and the rest seemed to look fine

**Comment by bilelmoussaoui** [comment]
I will backport and do a release later today

**Pull request merged**
