### PR TITLE
color fixes 0.8

### PR DESCRIPTION
**Pull request by wash2**
Should the color fixes be applied to 0.7? I guess the change to `receive_accent_color_changed` is breaking, so I'm not sure.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
> Should the color fixes be applied to 0.7? I guess the change to receive_accent_color_changed is breaking, so I'm not sure.

It is that is true, but the old implementation was just wrong. It would have never worked, so it is ok to break API here.

**Comment by wash2** [comment]
Is failing CI blocking a merge?

**Comment by bilelmoussaoui** [comment]
Yes, please target 0.8 branch. I won't be updating the 0.7 version anymore.

**Comment by bilelmoussaoui** [comment]
Thanks a lot ! will be doing a fix release sometime in the future once more fixes are collected

**Pull request merged**
